#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          BoxLeftMotor,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          BoxRightMotor, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     LeftMotors,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightMotors,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     LiftMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     BoxMotor,      tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
	//declare variables
	int nMotorPower;
  int nDirection;
  //FTC initial code
  initializeRobot();
  waitForStart();   // wait for start of tele-op phase
  //main teleop loop
  while(true){
  	getJoystickSettings(joystick); // Get current joystick settings
    nMotorPower = joystick.joy1_y1;
    nDirection = joystick.joy1_x1;
    if (nDirection < 0){ // Turn left
    	motor[motorD] = nMotorPower; // use power settings from Y-axis
    	motor[motorE] = nMotorPower * (64 + nDirection) / 64;
    }else{ // Turn right
    	motor[motorD] = nMotorPower; // use power settings from Y-axis
    	motor[motorE] = nMotorPower * (64 - nDirection) / 64;
    }
  		if(joy1Btn(1) == 1){ // If Joy1-Button1 is pressed:
      	motor[motorA] = 100;              // Turn Motor A On at full power
    	}else{                         // If Joy1-Button1 is NOT pressed:
     		motor[motorA] = 0;                 // Turn Motor A Off
			}
}
if(joy1Btn(1) == 1)
{
	motor[motorB] = 50;
}
else{
	motor[motorB] = 0;
}
}
